apiVersion: skaffold/v1beta10
kind: Config

profiles:
  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      kustomize:
        path: "./kustomize/overlays/microk8s"
        flags:
          apply:
            - --validate=false  ## Skaffold turns CRDs into invalid yaml (https://github.com/GoogleContainerTools/skaffold/issues/1737)

build:
  artifacts:
    - image: retraced-api
      context: "./api"
      docker:
        dockerfile: ./Dockerfile.skaffold

    # - image: retraced-logs-viewer
    #   context: "./logs-viewer"
    #   sync:
    #     manual:
    #       - src: "src/**/*.jsx"
    #         dest: "./"
    #       - src: "src/**/*.js"
    #         dest: "./"
    #       - src: "src/**/*.png"
    #         dest: "./"
    #       - src: "src/**/*.scss"
    #         dest: "./"
    #       - src: "src/**/*.css"
    #         dest: "./"
    #   docker:
    #     dockerfile: ./Dockerfile.skaffold

    # - image: retraced-admin
    #   context: "./admin"
    #   sync:
    #     manual:
    #       - src: "src/**/*.jsx"
    #         dest: "./"
    #       - src: "src/**/*.js"
    #         dest: "./"
    #       - src: "src/**/*.png"
    #         dest: "./"
    #       - src: "src/**/*.scss"
    #         dest: "./"
    #       - src: "src/**/*.css"
    #         dest: "./"
    #   docker:
    #     dockerfile: ./Dockerfile.skaffold

deploy:
  kustomize:
    path: "./kustomize/overlays/dev"
