apiVersion: v1
kind: Service
metadata:
  labels:
    app: auditlog
    tier: nsq
  name: nsqd
  namespace: auditlog-platform
spec:
  ports:
  - name: tcp
    port: 4150
    targetPort: 4150
  - name: http
    port: 4151
    targetPort: 4151
  selector:
    app: auditlog
    tier: nsq
  type: ClusterIP