apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: retraced-config
spec:
  groups:
    - name: retraced
      title: Retraced
      description: Retraced Configuration
      items:
        - name: hmac_secret_admin
          title: HMAC Admin Secret
          type: password
          default: 'retraced'
        - name: hmac_secret_view
          title: HMAC View Secret
          type: password
          default: 'retraced'