apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: cron
  template:
    metadata:
      labels:
        app: auditlog
        dest: nsq
        source: cron
        tier: cron
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - /usr/local/bin/replicated-auditlog-cron /crontab | grep ERRO
        env:
        - name: NSQD_HOST
          valueFrom:
            secretKeyRef:
              key: NSQD_HOST
              name: auditlog
        - name: NSQD_HTTP_PORT
          valueFrom:
            secretKeyRef:
              key: NSQD_HTTP_PORT
              name: auditlog
        - name: RETRACED_DISABLE_GEOSYNC
          value: "1"
        - name: ELASTICSEARCH_CAFILE
          value: "/etc/selasticsearch-certs/ca.crt"
        image: registry.replicated.com/library/retraced:1.4.6
        imagePullPolicy: IfNotPresent
        name: cron
        resources:
          requests:
            cpu: 10m
          limits:
            cpu: 100m
        volumeMounts:
        - name: elasticsearch-certs
          readOnly: true
          mountPath: "/etc/selasticsearch-certs"
      imagePullSecrets:
      - name: auditlog-imagepull-secret
      volumes:
      - name: elasticsearch-certs
        secret:
          secretName: auditlog-platform-es-http-certs-public
