apiVersion: v1
kind: Secret
metadata:
  labels:
    app: auditlog
    retraceddev: "1"
  name: auditlog
stringData:
  API_BASE_URL_PATH: /auditlog
  API_TOKEN: ""
  DB_TOKEN: ""
  ELASTICSEARCH_NODES: http://user:password@retraced-elasticsearch:9200
  HMAC_SECRET_ADMIN: xxxxxxx
  HMAC_SECRET_VIEWER: xxxxxxxxx
  MANDRILL_KEY: ""
  NSQD_HOST: retraced-nsqd
  NSQD_HTTP_PORT: "4151"
  NSQD_TCP_PORT: "4150"
  POSTGRES_DATABASE: retraced
  POSTGRES_HOST: retraced-postgres
  POSTGRES_PASSWORD: password
  POSTGRES_POOL_SIZE: "10"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: retraced
  PROCESSOR_TOKEN: ""
  RETRACED_API_BASE: http://localhost:3000/auditlog
  STAGE: ""
  STATSD_HOST: ""
  STATSD_PORT: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auditlog
    retraceddev: "1"
    tier: api
  name: retraced-api
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: auditlog
    retraceddev: "1"
    tier: api
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auditlog
    retraceddev: "1"
    tier: nsq
  name: retraced-nsqd
spec:
  ports:
  - name: tcp
    port: 4150
    targetPort: 4150
  - name: http
    port: 4151
    targetPort: 4151
  selector:
    app: auditlog
    retraceddev: "1"
    tier: nsq
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    retraceddev: "1"
  name: retraced-api
spec:
  replicas: 1
  selector:
    matchLabels:
      retraceddev: "1"
      tier: api
  template:
    metadata:
      labels:
        app: auditlog
        retraceddev: "1"
        tier: api
    spec:
      containers:
      - command:
        - node
        - --inspect=0.0.0.0
        - -r
        - ts-node/register
        - src/index.ts
        env:
        - name: EXPORT_PAGE_SIZE_INTERNAL
          value: "2"
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              key: API_TOKEN
              name: auditlog
        - name: PG_SEARCH
          value: ""
        envFrom:
        - secretRef:
            name: auditlog
        image: registry.replicated.com/library/retraced:1.4.6
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 9229
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
      imagePullSecrets:
      - name: auditlog-imagepull-secret
      initContainers:
      - args:
        - -c
        - node -r ts-node/register src/retracedctl.ts bootstrap --projectName   "$BOOTSTRAP_PROJECT_NAME"
          --projectId     "$BOOTSTRAP_PROJECT_ID" --environmentId "$BOOTSTRAP_ENVIRONMENT_ID"
          --apiKey        "$BOOTSTRAP_API_TOKEN"
        command:
        - /bin/sh
        env:
        - name: BOOTSTRAP_PROJECT_NAME
          value: dev
        - name: BOOTSTRAP_PROJECT_ID
          value: dev
        - name: BOOTSTRAP_ENVIRONMENT_ID
          value: dev
        - name: BOOTSTRAP_API_TOKEN
          value: dev
        envFrom:
        - secretRef:
            name: auditlog
        image: registry.replicated.com/library/retraced:1.4.6
        name: bootstrap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    retraceddev: "1"
  name: retraced-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      retraceddev: "1"
      tier: cron
  template:
    metadata:
      labels:
        app: auditlog
        dest: nsq
        retraceddev: "1"
        source: cron
        tier: cron
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /usr/local/bin/replicated-auditlog-cron /crontab 2>&1 | grep ERRO
        env:
        - name: NSQD_HOST
          valueFrom:
            secretKeyRef:
              key: NSQD_HOST
              name: auditlog
        - name: NSQD_HTTP_PORT
          valueFrom:
            secretKeyRef:
              key: NSQD_HTTP_PORT
              name: auditlog
        - name: RETRACED_DISABLE_GEOSYNC
          value: "1"
        image: registry.replicated.com/library/retraced:1.4.6
        imagePullPolicy: IfNotPresent
        name: cron
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 10m
      imagePullSecrets: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: retraced
    retraceddev: "1"
    tier: dbutil
  name: retraced-dbutil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retraced
      retraceddev: "1"
      tier: dbutil
  template:
    metadata:
      labels:
        app: retraced
        retraceddev: "1"
        tier: dbutil
    spec:
      containers:
      - command:
        - /bin/sleep
        - infinity
        envFrom:
        - secretRef:
            name: auditlog
        image: registry.replicated.com/library/retraced:1.4.6
        name: dbutil
      imagePullSecrets:
      - name: auditlog-imagepull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    retraceddev: "1"
  name: retraced-nsqd
spec:
  replicas: 1
  selector:
    matchLabels:
      retraceddev: "1"
      tier: nsq
  template:
    metadata:
      labels:
        app: auditlog
        retraceddev: "1"
        tier: nsq
    spec:
      containers:
      - args:
        - -c
        - nsqd -statsd-address ${STATSD_HOST}:${STATSD_PORT} -statsd-prefix "nsqd."
        command:
        - /bin/sh
        env:
        - name: STATSD_HOST
          valueFrom:
            secretKeyRef:
              key: STATSD_HOST
              name: auditlog
        - name: STATSD_PORT
          valueFrom:
            secretKeyRef:
              key: STATSD_PORT
              name: auditlog
        image: nsqio/nsq:v1.0.0-compat
        name: nsqd
        ports:
        - containerPort: 4150
        - containerPort: 4151
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    retraceddev: "1"
  name: retraced-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      retraceddev: "1"
      tier: processor
  template:
    metadata:
      labels:
        app: auditlog
        retraceddev: "1"
        tier: processor
    spec:
      containers:
      - command:
        - node
        - --inspect=0.0.0.0
        - -r
        - ts-node/register
        - src/_processor/index.ts
        env:
        - name: TMPDIR
          value: /tmp
        - name: NO_WARP_PIPE
          value: "1"
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              key: PROCESSOR_TOKEN
              name: auditlog
        - name: PG_SEARCH
          value: ""
        envFrom:
        - secretRef:
            name: auditlog
        image: registry.replicated.com/library/retraced:1.4.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /livez
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 1
        name: processor
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 1
          successThreshold: 2
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /tmp
          name: tmpdir
      imagePullSecrets: []
      volumes:
      - emptyDir: {}
        name: tmpdir
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    retraceddev: "1"
  name: retraced-migrate-es-1-4-6
spec:
  template:
    metadata:
      labels:
        retraceddev: "1"
    spec:
      containers:
      - command:
        - node
        - --inspect=0.0.0.0
        - -r
        - ts-node/register
        - src/_db/runner-lite.ts
        - es
        env:
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              key: DB_TOKEN
              name: auditlog
        envFrom:
        - secretRef:
            name: auditlog
        image: registry.replicated.com/library/retraced:1.4.6
        name: db
      imagePullSecrets: []
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    retraceddev: "1"
  name: retraced-migrate-pg-1-4-6
spec:
  template:
    metadata:
      labels:
        retraceddev: "1"
    spec:
      containers:
      - command:
        - node
        - --inspect=0.0.0.0
        - -r
        - ts-node/register
        - src/_db/runner-lite.ts
        - pg
        env:
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              key: DB_TOKEN
              name: auditlog
        - name: SCHEMA_PATH
          value: /src/migrations/pg10
        envFrom:
        - secretRef:
            name: auditlog
        image: registry.replicated.com/library/retraced:1.4.6
        imagePullPolicy: IfNotPresent
        name: db
      imagePullSecrets: []
      restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    retraceddev: "1"
  name: retraced-integrationtest
spec:
  containers:
  - command:
    - npx
    - mocha
    - -r
    - ts-node/register
    - integration/test/**/*.ts
    env:
    - name: PUBLISHER_API_ENDPOINT
      value: http://retraced-api:3000/auditlog
    - name: PROJECT_ID
      value: dev
    - name: ENVIRONMENT_ID
      value: dev
    - name: PUBLISHER_API_KEY
      value: dev
    - name: ES_INDEX_WAIT_MS
      value: "2000"
    envFrom:
    - secretRef:
        name: auditlog
    image: registry.replicated.com/library/retraced
    name: tests
  restartPolicy: OnFailure
