apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: retraced-postgres
  namespace: '{{repl Namespace}}'
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app: postgres
  type: ClusterIP