apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: processor
  template:
    metadata:
      labels:
        app: auditlog
        tier: processor
    spec:
      containers:
      - command:
        - /src/processor
        env:
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: STATSD_PORT
          value: "8125"
        - name: TMPDIR
          value: /tmp
        - name: NO_WARP_PIPE
          value: "1"
        - name: LOG_LEVEL
          value: "info"
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              key: PROCESSOR_TOKEN
              name: auditlog
        - name: ELASTICSEARCH_CAFILE
          value: "/etc/selasticsearch-certs/ca.crt"
        envFrom:
        - secretRef:
            name: auditlog
        image: registry.replicated.com/library/retraced:1.4.6
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /livez
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 1
        name: processor
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 1
          successThreshold: 2
        volumeMounts:
        - mountPath: /tmp
          name: tmpdir
        - name: elasticsearch-certs
          readOnly: true
          mountPath: "/etc/selasticsearch-certs"
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
      imagePullSecrets:
      - name: auditlog-imagepull-secret
      volumes:
      - emptyDir: {}
        name: tmpdir
      - name: elasticsearch-certs
        secret:
          secretName: auditlog-platform-es-http-certs-public