apiVersion: v1
kind: Service
metadata:
  labels:
    app: auditlog
    retraceddev: "1"
    tier: nsq
  name: retraced-nsqd
  namespace: '{{repl Namespace}}'
spec:
  ports:
  - name: tcp
    port: 4150
    targetPort: 4150
  - name: http
    port: 4151
    targetPort: 4151
  selector:
    app: auditlog
    retraceddev: "1"
    tier: nsq
  type: ClusterIP