apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: retraced
    tier: dbutil
  name: dbutil
  namespace: auditlog-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retraced
      tier: dbutil
  template:
    metadata:
      labels:
        app: retraced
        tier: dbutil
    spec:
      containers:
      - command:
        - /bin/sleep
        - infinity
        envFrom:
        - secretRef:
            name: auditlog
        image: registry.replicated.com/library/retraced:1.4.6
        name: dbutil
      imagePullSecrets:
      - name: auditlog-imagepull-secret
