apiVersion: v1
kind: Secret
metadata:
  labels:
    app: auditlog
    retraceddev: "1"
  name: auditlog
  namespace: '{{repl Namespace}}'
stringData:
  # a comma-separated list of one or more elasticsearch connection strings
  ELASTICSEARCH_NODES: http://user:password@retraced-elasticsearch:9200
  # secure random strings for use in session signing
  HMAC_SECRET_ADMIN: '{{repl ConfigOption "hmac_secret_admin"}}'
  HMAC_SECRET_VIEWER: '{{repl ConfigOption "hmac_secret_view"}}'
  # nsq settings, these shouldn't change
  NSQD_HOST: retraced-nsqd
  NSQD_TCP_PORT: "4150"
  NSQD_HTTP_PORT: "4151"
  # postgres settings
  POSTGRES_POOL_SIZE: "10"
  POSTGRES_USER: "retraced"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "retraced-postgres"
  POSTGRES_DATABASE: "retraced"
  POSTGRES_PORT: "5432"
  # optional, tokens to report errors to bugsnag
  PROCESSOR_TOKEN: ""
  API_TOKEN: ""
  DB_TOKEN: ""
  # the URL that browser clients will use to communicate with retraced. Can be omitted if not using embedded viewer
  RETRACED_API_BASE: "http://localhost:3000/auditlog"
  API_BASE_URL_PATH: "/auditlog"
  # statsd settings
  STATSD_HOST: ""
  STATSD_PORT: ""
  # usually one of `staging` or `production`
  STAGE: ""
  # optional, a mandrill key for email alerts
  MANDRILL_KEY: ""support-bundle.yaml