apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-es-1-4-2
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  template:
    spec:
      imagePullSecrets:
      - name: auditlog-imagepull-secret
      restartPolicy: Never
      containers:
      - name: db
        image: registry.replicated.com/shipretraced/retraced:1.4.2
        command:
        - node
        - --inspect=0.0.0.0
        - -r
        - ts-node/register
        - src/_db/runner-lite.ts
        - es
        - up
        envFrom:
        - secretRef:
            name: auditlog
        env:
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              name: auditlog
              key: DB_TOKEN

